name: flutter_observable
description: A simple observable with corresponding controller and builder.
version: 0.2.0
author: Linus Unnebäck <linus@folkdatorn.se>
homepage: https://github.com/LinusU/flutter_observable

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
